# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               KK的自留地
tagline:             '一笑寂寥'
description:         
url:                 
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              kk
  url:               
  email:             kstzyy@gmail.com

# Custom vars
version:             1.0.0
