# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               KK的自留地
tagline:             '夫天地者，万物之逆旅；光阴者，百代之过客'
description:         欲穷千里目，更上一层楼
url:                 
baseurl:             'daoism.me'
paginate:            5

# About/contact
author:
  name:              kk
  url:               
  email:             kstzyy@gmail.com

# Custom vars
version:             1.0.0
